import { IconType } from "react-icons";
import { DiMsqlServer } from "react-icons/di";

import {
  BsFileEarmarkExcelFill,
  BsFileEarmarkPptFill,
  BsMicrosoft,
  BsEnvelopeAtFill,
  BsFileBarGraphFill,
  BsCameraVideoFill,
} from "react-icons/bs";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiComputerDesktop,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiPhp,
  SiTypescript,
  SiFastapi,
  SiLaravel,
  SiReact,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiMysql,
  SiPostgresql,
  SiPrometheus,
  SiGrafana,
  SiRedis,
  SiCelery,
  SiPostman,
  SiDocker,
  SiGit,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobeaudition,
  SiAdobepremierepro,
  SiObsstudio,
  SiCanva,
  SiSocketdotio,
  SiStreamlit,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaBrain,
  FaDatabase,
  FaCode,
  FaGears,
  FaNetworkWired,
  FaMagnifyingGlass,
  FaServer,
  FaN,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  php: SiPhp,
  nextjs: SiNextdotjs,
  react: SiReact,
  fastapi: SiFastapi,
  laravel: SiLaravel,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  mysql: SiMysql,
  sqlserver: DiMsqlServer,
  postgresql: SiPostgresql,
  supabase: SiSupabase,
  prometheus: SiPrometheus,
  grafana: SiGrafana,
  redis: SiRedis,
  celery: SiCelery,
  postman: SiPostman,
  docker: SiDocker,
  git: SiGit,
  figma: SiFigma,
  powerbi: BsFileBarGraphFill,
  office: BsMicrosoft,
  excel: BsFileEarmarkExcelFill,
  powerpoint: BsFileEarmarkPptFill,
  outlook: BsEnvelopeAtFill,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  photoshop: SiAdobephotoshop,
  illustrator: SiAdobeillustrator,
  audition: SiAdobeaudition,
  premiere: SiAdobepremierepro,
  obs: SiObsstudio,
  canva: SiCanva,
  vmix: BsCameraVideoFill,
  websocket: SiSocketdotio,
  streamlit: SiStreamlit,
  "internetinformationservice(iis)": FaServer,
  laravel12: SiLaravel,
  rag: FaMagnifyingGlass,
  llm: FaBrain,
  vectordatabase: FaDatabase,
  webdev: FaCode,
  deeplearning: FaNetworkWired,
  mlops: FaGears,
  RDP: HiComputerDesktop,
  NSSM: FaN,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
